apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: qru1oqdnu-nodejs 
  janus-idp.io/tekton: qru1oqdnu-nodejs
  backstage.io/kubernetes-id: qru1oqdnu-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: qru1oqdnu-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml