apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: qru1oqdnu-nodejs
  janus-idp.io/tekton: qru1oqdnu-nodejs
  backstage.io/kubernetes-id: qru1oqdnu-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: qru1oqdnu-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
